### ISSUE TITLE
can you give me example how to decrypt AESGCM ? owo

### ISSUE THREAD

**Issue by agunq** [randomlogin/ece#7]
i try to translate code from nodejs to ruby, what i need to do now is to decrypt raw_data 

this is the code in javascript

`
const crypto = require('crypto');
const ece = require('http_ece');

module.exports = decrypt;

// https://tools.ietf.org/html/draft-ietf-webpush-encryption-03
function decrypt(object, keys) {
  const cryptoKey = object.appData.find(item => item.key === 'crypto-key');
  if (!cryptoKey) throw new Error('crypto-key is missing');
  const salt = object.appData.find(item => item.key === 'encryption');
  if (!salt) throw new Error('salt is missing');
  const dh = crypto.createECDH('prime256v1');
  dh.setPrivateKey(keys.privateKey, 'base64');
  const params = {
    version    : 'aesgcm',
    authSecret : keys.authSecret,
    dh         : cryptoKey.value.slice(3),
    privateKey : dh,
    salt       : salt.value.slice(5),
  };
  const decrypted = ece.decrypt(object.rawData, params);
  return JSON.parse(decrypted);
}
`

the credential i got with ruby 
crypto_key, salt, private_key, secret, and raw_data(data that need to decrypt)

**Comment by randomlogin** [comment]
Unfortunately no, it was too long ago when I was doing, it. I encourage you to try to modify example and see the source code.
